package backup

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"sort"
	"strings"
)

// dbDumpName is the snapshot filename for a database dump. It hashes container +
// db with a NUL joiner so two different (container, db) pairs can never collide
// onto the same file — sanitize() alone would, because it maps the separator and
// other characters to '_'. backup and restore both call this, so the names match.
func dbDumpName(container, db string) string {
	h := sha256.Sum256([]byte(container + "\x00" + db))
	return "db_" + hex.EncodeToString(h[:6]) + ".sql"
}

// sourceEnv is the snippet that loads a job's secrets and exports them so the
// child processes (restic, docker) inherit RESTIC_REPOSITORY, the S3 keys, etc.
// `set -a` makes every assignment from the sourced file an export.
func sourceEnv(id string) string {
	return "set -a; . " + shellQuote(jobEnv(id)) + "; set +a"
}

// RenderScript produces the per-job backup runner: dump databases, tar named
// volumes, copy the compose dir, then `restic backup` + `restic forget`.
// Database passwords are sniffed from the live container at run time (never
// stored), so the script stays correct even if credentials rotate.
func RenderScript(job Job) string {
	var b strings.Builder
	w := func(s string) { b.WriteString(s + "\n") }

	w("#!/bin/sh")
	w("# Generated by vps-manager. Backup job: " + job.Name + " (" + job.ID + ")")
	w("set -e")
	w("export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin")
	w(sourceEnv(job.ID))
	w(`STAGE="$(mktemp -d /tmp/vps-bak.XXXXXX)"`)
	w(`START=$(date +%s)`)
	// Heartbeat: a background loop so long, quiet steps (a big volume tar, or the
	// restic upload — which prints nothing to a non-terminal pipe) still show a
	// pulse with the staged size and elapsed time, instead of looking frozen.
	w(`( while true; do sleep 10; echo "  … working — staged $(du -sh "$STAGE" 2>/dev/null | cut -f1), $(( $(date +%s) - START ))s elapsed"; done ) & HB=$!`)
	w(`trap 'kill "$HB" 2>/dev/null; rm -rf "$STAGE"' EXIT`)
	w(`echo "[$(date -Is 2>/dev/null || date)] backup ` + job.ID + ` starting"`)

	if job.IncludeCompose && job.StackPath != "" {
		w("")
		w("echo '→ copying compose directory'")
		w(`mkdir -p "$STAGE/compose"`)
		w("cp -a " + shellQuote(strings.TrimRight(job.StackPath, "/")+"/.") + ` "$STAGE/compose/" 2>/dev/null || echo '  (nothing to copy)'`)
	}

	for _, d := range job.Databases {
		w("")
		w("echo " + shellQuote("→ dumping "+d.Engine+" database "+d.DB+" from "+d.Container))
		out := `"$STAGE/` + dbDumpName(d.Container, d.DB) + `"`
		c := shellQuote(d.Container)
		switch d.Engine {
		case "postgres":
			w(`PW="$(docker exec ` + c + ` printenv POSTGRES_PASSWORD 2>/dev/null || true)"`)
			w("docker exec -e PGPASSWORD=\"$PW\" " + c + " pg_dump -U " + shellQuote(d.User) + " " + shellQuote(d.DB) + " > " + out)
		case "mysql":
			w(`PW="$(docker exec ` + c + ` printenv MYSQL_ROOT_PASSWORD 2>/dev/null || true)"`)
			w(`[ -n "$PW" ] || PW="$(docker exec ` + c + ` printenv MYSQL_PASSWORD 2>/dev/null || true)"`)
			w("docker exec -e MYSQL_PWD=\"$PW\" " + c + " mysqldump -u " + shellQuote(d.User) + " " + shellQuote(d.DB) + " > " + out)
		}
		w(`echo "    ✓ dumped ($(du -h ` + out + ` 2>/dev/null | cut -f1))"`)
	}

	for _, vol := range job.Volumes {
		w("")
		w("echo " + shellQuote("→ archiving volume "+vol))
		archive := `"/dest/vol_` + sanitize(vol) + `.tar.gz"`
		host := `"$STAGE/vol_` + sanitize(vol) + `.tar.gz"`
		w("docker run --rm -v " + shellQuote(vol) + `:/src:ro -v "$STAGE":/dest alpine tar czf ` + archive + " -C /src .")
		w(`echo "    ✓ archived ($(du -h ` + host + ` 2>/dev/null | cut -f1))"`)
	}

	w("")
	w(`echo "→ uploading $(du -sh "$STAGE" 2>/dev/null | cut -f1) to the bucket with restic…"`)
	w(`restic backup "$STAGE" --tag vps-manager --tag ` + shellQuote(job.ID))
	if forget := forgetFlags(job.Retention); forget != "" {
		w("echo '→ applying retention'")
		w("restic forget " + forget + " --prune")
	}
	w(`echo "[$(date -Is 2>/dev/null || date)] backup ` + job.ID + ` done"`)
	return b.String()
}

// RenderCron is the /etc/cron.d drop-in: run as root, append output to a log.
func RenderCron(job Job) string {
	return fmt.Sprintf("%s  root  %s >> %s 2>&1\n",
		strings.TrimSpace(job.Schedule), jobScript(job.ID), logFile(job.ID))
}

// forgetFlags turns a retention policy into restic forget flags (empty if none).
func forgetFlags(r RetentionPolicy) string {
	var f []string
	if r.KeepLast > 0 {
		f = append(f, fmt.Sprintf("--keep-last %d", r.KeepLast))
	}
	if r.KeepDaily > 0 {
		f = append(f, fmt.Sprintf("--keep-daily %d", r.KeepDaily))
	}
	if r.KeepWeekly > 0 {
		f = append(f, fmt.Sprintf("--keep-weekly %d", r.KeepWeekly))
	}
	if r.KeepMonthly > 0 {
		f = append(f, fmt.Sprintf("--keep-monthly %d", r.KeepMonthly))
	}
	return strings.Join(f, " ")
}

// ───────── env file ─────────

// resticRepo builds the restic S3 repository URL. restic requires an explicit
// scheme for non-Amazon endpoints (Cloudflare R2, Backblaze B2, MinIO…), so we
// add https:// when the endpoint has none — harmless for AWS too. The bucket is
// appended path-style, which is what restic's bucket-lookup=auto selects for any
// non-Amazon/Google host.
func resticRepo(b BucketRef) string {
	ep := strings.TrimRight(strings.TrimSpace(b.Endpoint), "/")
	if ep != "" && !strings.Contains(ep, "://") {
		ep = "https://" + ep
	}
	repo := "s3:" + ep + "/" + strings.Trim(b.Bucket, "/")
	if p := strings.Trim(b.Prefix, "/"); p != "" {
		repo += "/" + p
	}
	return repo
}

// isR2 reports whether the endpoint is a Cloudflare R2 host.
func isR2(endpoint string) bool {
	return strings.Contains(strings.ToLower(endpoint), "r2.cloudflarestorage.com")
}

// buildEnv merges new secrets over whatever already exists on the VPS (so blank
// fields on edit keep the stored value), and always refreshes the repo/region
// from the current bucket settings.
func buildEnv(b BucketRef, s Secrets, existing map[string]string) map[string]string {
	env := map[string]string{}
	for k, v := range existing {
		env[k] = v
	}
	env["RESTIC_REPOSITORY"] = resticRepo(b)
	region := strings.TrimSpace(b.Region)
	if region == "" && isR2(b.Endpoint) {
		// R2's canonical region is "auto". Setting it explicitly also bypasses
		// restic/minio-go's GetBucketLocation probe — the classic R2 init failure
		// on older restic — and is harmless on any version.
		region = "auto"
	}
	if region != "" {
		env["AWS_DEFAULT_REGION"] = region
	}
	if s.AccessKey != "" {
		env["AWS_ACCESS_KEY_ID"] = s.AccessKey
	}
	if s.SecretKey != "" {
		env["AWS_SECRET_ACCESS_KEY"] = s.SecretKey
	}
	if s.ResticPassword != "" {
		env["RESTIC_PASSWORD"] = s.ResticPassword
	}
	return env
}

// renderEnv writes KEY='value' lines (single-quoted so any character survives a
// `. file` source). readEnv reverses the quoting.
func renderEnv(env map[string]string) string {
	order := []string{"RESTIC_REPOSITORY", "RESTIC_PASSWORD", "AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_DEFAULT_REGION"}
	seen := map[string]bool{}
	var b strings.Builder
	emit := func(k string) {
		v, ok := env[k]
		if !ok || seen[k] {
			return
		}
		seen[k] = true
		b.WriteString(k + "=" + shellQuote(v) + "\n")
	}
	for _, k := range order {
		emit(k)
	}
	var rest []string
	for k := range env {
		if !seen[k] {
			rest = append(rest, k)
		}
	}
	sort.Strings(rest)
	for _, k := range rest {
		emit(k)
	}
	return b.String()
}

// shellUnquote reverses shellQuote for values read back from an env file.
func shellUnquote(s string) string {
	if len(s) >= 2 && s[0] == '\'' && s[len(s)-1] == '\'' {
		return strings.ReplaceAll(s[1:len(s)-1], `'\''`, `'`)
	}
	return s
}

// sanitize reduces an arbitrary name to a filename-safe token.
func sanitize(s string) string {
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '.', r == '_', r == '-':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	if b.Len() == 0 {
		return "x"
	}
	return b.String()
}
