// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {db} from '../models';
import {migration} from '../models';
import {backup} from '../models';
import {docker} from '../models';
import {sftp} from '../models';
import {maintenance} from '../models';
import {provision} from '../models';
import {caddy} from '../models';
import {main} from '../models';

export function AddVPS(arg1:config.VPS):Promise<void>;

export function ChmodRemoteFile(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function ChooseOpenPath():Promise<string>;

export function ChooseSavePath(arg1:string,arg2:string):Promise<string>;

export function ChownRemoteFile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function ClearSudoPassword(arg1:string):Promise<void>;

export function ClipboardText():Promise<string>;

export function CloseShell(arg1:string):Promise<void>;

export function Connect(arg1:string):Promise<main.ConnectStatus>;

export function TrustHostKey(arg1:string):Promise<main.ConnectStatus>;

export function ForgetHostKey(arg1:string):Promise<void>;

export function SystemUsage(arg1:string,arg2:boolean):Promise<maintenance.Usage>;

export function PruneDocker(arg1:string,arg2:maintenance.PruneOptions,arg3:boolean):Promise<void>;

export function SystemLargestImages(arg1:string,arg2:number,arg3:boolean):Promise<Array<maintenance.Image>>;

export function ProvisionDatabaseEngines():Promise<Array<provision.Engine>>;

export function ProvisionDatabase(arg1:string,arg2:provision.Spec,arg3:boolean):Promise<provision.Result>;

export function DetectCaddyProxy(arg1:string,arg2:boolean):Promise<caddy.ProxyInfo>;

export function ExposeServiceDomain(arg1:string,arg2:caddy.ExposeSpec,arg3:boolean):Promise<void>;

export function CloudflareUpsert(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function ContainerLogs(arg1:string,arg2:string,arg3:number):Promise<string>;

export function DBDeleteRow(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:{[key: string]: any},arg7:boolean):Promise<string>;

export function DBInsertRow(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:{[key: string]: any},arg7:boolean):Promise<string>;

export function DBListDatabases(arg1:string,arg2:string,arg3:boolean):Promise<Array<string>>;

export function DBListTables(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<Array<db.Table>>;

export function DBQuery(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<db.QueryResult>;

export function DBTableColumns(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean):Promise<Array<db.Column>>;

export function DBTableRows(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number,arg7:number,arg8:boolean):Promise<db.QueryResult>;

export function DBUpdateRow(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:{[key: string]: any},arg7:{[key: string]: any},arg8:boolean):Promise<string>;

export function DefaultDownloadDir():Promise<string>;

export function DeleteBackupJob(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function DeleteDeployment(arg1:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteRemoteFile(arg1:string,arg2:string):Promise<void>;

export function DeleteVPS(arg1:string):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function DiscoverComposeContext(arg1:string,arg2:string,arg3:boolean):Promise<migration.ComposeContext>;

export function DiscoverStacks(arg1:string,arg2:string,arg3:boolean):Promise<Array<migration.SubStack>>;

export function DownloadFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function FindComposeFile(arg1:string,arg2:string):Promise<string>;

export function ForgetBackupSnapshot(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function HasSudoPassword(arg1:string):Promise<boolean>;

export function InspectMigration(arg1:string,arg2:string,arg3:Array<string>,arg4:string,arg5:boolean):Promise<migration.Inventory>;

export function InspectTeardown(arg1:string,arg2:string,arg3:Array<string>,arg4:string,arg5:boolean):Promise<migration.Inventory>;

export function IsConnected(arg1:string):Promise<boolean>;

export function ListBackupJobs(arg1:string,arg2:boolean):Promise<Array<backup.Job>>;

export function ListBackupSnapshots(arg1:string,arg2:string,arg3:boolean):Promise<Array<backup.Snapshot>>;

export function ListContainers(arg1:string,arg2:string):Promise<Array<docker.Container>>;

export function ListDBContainers(arg1:string,arg2:boolean,arg3:string):Promise<Array<db.Container>>;

export function ListDeployments():Promise<Array<config.Deployment>>;

export function ListFiles(arg1:string,arg2:string):Promise<Array<sftp.FileInfo>>;

export function ListProjects():Promise<Array<config.Project>>;

export function ListVPS():Promise<Array<config.VPS>>;

export function LocalAvailable():Promise<boolean>;

export function LocalStartDir():Promise<string>;

export function LocalUnavailableReason():Promise<string>;

export function MakeDir(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function ReadRemoteFile(arg1:string,arg2:string):Promise<string>;

export function ResizeShell(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RestartContainer(arg1:string,arg2:string):Promise<void>;

export function RestoreBackup(arg1:string,arg2:backup.Job,arg3:backup.Secrets,arg4:backup.RestoreOptions,arg5:boolean):Promise<void>;

export function RunBackupNow(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function RunCommand(arg1:string,arg2:string):Promise<main.CommandResult>;

export function RunContainerCommand(arg1:string,arg2:string,arg3:string):Promise<main.CommandResult>;

export function RunDeploy(arg1:string):Promise<void>;

export function RunMigration(arg1:string,arg2:string,arg3:migration.RunOptions,arg4:boolean):Promise<void>;

export function RunMultiMigration(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>,arg6:boolean):Promise<void>;

export function SaveBackupJob(arg1:string,arg2:backup.Job,arg3:backup.Secrets,arg4:boolean):Promise<backup.Job>;

export function SaveDeployment(arg1:config.Deployment):Promise<config.Deployment>;

export function SaveProject(arg1:config.Project,arg2:config.VPS):Promise<config.Project>;

export function SetClipboardText(arg1:string):Promise<void>;

export function SetSudoPassword(arg1:string,arg2:string):Promise<void>;

export function StartContainer(arg1:string,arg2:string):Promise<void>;

export function StartShell(arg1:string,arg2:number,arg3:number):Promise<void>;

export function StatRemoteFile(arg1:string,arg2:string):Promise<main.PathInfo>;

export function StopContainer(arg1:string,arg2:string):Promise<void>;

export function TeardownStack(arg1:string,arg2:docker.TeardownOptions,arg3:boolean):Promise<void>;

export function TestBackupTarget(arg1:string,arg2:backup.BucketRef,arg3:backup.Secrets,arg4:boolean):Promise<void>;

export function UpdateVPS(arg1:config.VPS):Promise<void>;

export function UploadFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WriteRemoteFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WriteShell(arg1:string,arg2:string):Promise<void>;
