// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddVPS(arg1) {
  return window['go']['main']['App']['AddVPS'](arg1);
}

export function ChooseOpenPath() {
  return window['go']['main']['App']['ChooseOpenPath']();
}

export function ChooseSavePath(arg1, arg2) {
  return window['go']['main']['App']['ChooseSavePath'](arg1, arg2);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function ContainerLogs(arg1, arg2, arg3) {
  return window['go']['main']['App']['ContainerLogs'](arg1, arg2, arg3);
}

export function DefaultDownloadDir() {
  return window['go']['main']['App']['DefaultDownloadDir']();
}

export function DeleteRemoteFile(arg1, arg2) {
  return window['go']['main']['App']['DeleteRemoteFile'](arg1, arg2);
}

export function ReadRemoteFile(arg1, arg2) {
  return window['go']['main']['App']['ReadRemoteFile'](arg1, arg2);
}

export function WriteRemoteFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteRemoteFile'](arg1, arg2, arg3);
}

export function DeleteVPS(arg1) {
  return window['go']['main']['App']['DeleteVPS'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function DownloadFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2, arg3);
}

export function IsConnected(arg1) {
  return window['go']['main']['App']['IsConnected'](arg1);
}

export function ListContainers(arg1) {
  return window['go']['main']['App']['ListContainers'](arg1);
}

export function ListFiles(arg1, arg2) {
  return window['go']['main']['App']['ListFiles'](arg1, arg2);
}

export function ListVPS() {
  return window['go']['main']['App']['ListVPS']();
}

export function RestartContainer(arg1, arg2) {
  return window['go']['main']['App']['RestartContainer'](arg1, arg2);
}

export function RunCommand(arg1, arg2) {
  return window['go']['main']['App']['RunCommand'](arg1, arg2);
}

export function RunContainerCommand(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunContainerCommand'](arg1, arg2, arg3);
}

export function StartContainer(arg1, arg2) {
  return window['go']['main']['App']['StartContainer'](arg1, arg2);
}

export function StopContainer(arg1, arg2) {
  return window['go']['main']['App']['StopContainer'](arg1, arg2);
}

export function UpdateVPS(arg1) {
  return window['go']['main']['App']['UpdateVPS'](arg1);
}

export function UploadFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2, arg3);
}

export function StartShell(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartShell'](arg1, arg2, arg3);
}

export function WriteShell(arg1, arg2) {
  return window['go']['main']['App']['WriteShell'](arg1, arg2);
}

export function ResizeShell(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeShell'](arg1, arg2, arg3);
}

export function CloseShell(arg1) {
  return window['go']['main']['App']['CloseShell'](arg1);
}

export function MakeDir(arg1, arg2, arg3) {
  return window['go']['main']['App']['MakeDir'](arg1, arg2, arg3);
}

export function StatRemoteFile(arg1, arg2) {
  return window['go']['main']['App']['StatRemoteFile'](arg1, arg2);
}

export function ChmodRemoteFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ChmodRemoteFile'](arg1, arg2, arg3, arg4);
}

export function ChownRemoteFile(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ChownRemoteFile'](arg1, arg2, arg3, arg4, arg5);
}

export function SetSudoPassword(arg1, arg2) {
  return window['go']['main']['App']['SetSudoPassword'](arg1, arg2);
}

export function HasSudoPassword(arg1) {
  return window['go']['main']['App']['HasSudoPassword'](arg1);
}

export function ClearSudoPassword(arg1) {
  return window['go']['main']['App']['ClearSudoPassword'](arg1);
}

export function ProbeSudo(arg1) {
  return window['go']['main']['App']['ProbeSudo'](arg1);
}

export function FindComposeFile(arg1, arg2) {
  return window['go']['main']['App']['FindComposeFile'](arg1, arg2);
}

export function InspectMigration(arg1, arg2, arg3) {
  return window['go']['main']['App']['InspectMigration'](arg1, arg2, arg3);
}

export function RunMigration(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RunMigration'](arg1, arg2, arg3, arg4);
}

export function ClipboardText() {
  return window['go']['main']['App']['ClipboardText']();
}

export function SetClipboardText(arg1) {
  return window['go']['main']['App']['SetClipboardText'](arg1);
}
