// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {docker} from '../models';
import {sftp} from '../models';
import {main} from '../models';

export function AddVPS(arg1:config.VPS):Promise<void>;

export function Connect(arg1:string):Promise<void>;

export function ContainerLogs(arg1:string,arg2:string,arg3:number):Promise<string>;

export function DefaultDownloadDir():Promise<string>;

export function DeleteRemoteFile(arg1:string,arg2:string):Promise<void>;

export function DeleteVPS(arg1:string):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function DownloadFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function IsConnected(arg1:string):Promise<boolean>;

export function ListContainers(arg1:string):Promise<Array<docker.Container>>;

export function ListFiles(arg1:string,arg2:string):Promise<Array<sftp.FileInfo>>;

export function ListVPS():Promise<Array<config.VPS>>;

export function RestartContainer(arg1:string,arg2:string):Promise<void>;

export function RunCommand(arg1:string,arg2:string):Promise<main.CommandResult>;

export function RunContainerCommand(arg1:string,arg2:string,arg3:string):Promise<main.CommandResult>;

export function StartContainer(arg1:string,arg2:string):Promise<void>;

export function StopContainer(arg1:string,arg2:string):Promise<void>;

export function UpdateVPS(arg1:config.VPS):Promise<void>;

export function UploadFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StartShell(arg1:string,arg2:number,arg3:number):Promise<void>;

export function WriteShell(arg1:string,arg2:string):Promise<void>;

export function ResizeShell(arg1:string,arg2:number,arg3:number):Promise<void>;

export function CloseShell(arg1:string):Promise<void>;

export function MakeDir(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function StatRemoteFile(arg1:string,arg2:string):Promise<main.PathInfo>;

export function ChmodRemoteFile(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function ChownRemoteFile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function SetSudoPassword(arg1:string,arg2:string):Promise<void>;

export function HasSudoPassword(arg1:string):Promise<boolean>;

export function ClearSudoPassword(arg1:string):Promise<void>;

export function ProbeSudo(arg1:string):Promise<string>;

export function FindComposeFile(arg1:string,arg2:string):Promise<string>;

export function InspectMigration(arg1:string,arg2:string,arg3:boolean):Promise<any>;

export function RunMigration(arg1:string,arg2:string,arg3:any,arg4:boolean):Promise<void>;

export function ClipboardText():Promise<string>;

export function SetClipboardText(arg1:string):Promise<void>;
